import {
  DELETE_PRODUCT,
  DELETE_PRODUCT_ERROR,
  DELETE_PRODUCT_SUCCESS,
  GET_PRODUCTS,
  GET_PRODUCTS_ERROR,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCT_BY_ID,
  GET_PRODUCT_BY_ID_ERROR,
  GET_PRODUCT_BY_ID_SUCCESS,
  SAVE_PRODUCT,
  SAVE_PRODUCT_ERROR,
  SAVE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT,
  UPDATE_PRODUCT_ERROR,
  UPDATE_PRODUCT_SUCCESS,
  VERIFICATION_PRODUCT_ID,
  VERIFICATION_PRODUCT_ID_ERROR,
  VERIFICATION_PRODUCT_ID_SUCCESS,
} from './product-state.actions';
import { selectProduct, selectProducts } from './product-state.select';

import { ProductEffects } from './product-state.effects';
import { ProductReducer } from './product-state.reducer';

export const productRoot = {
  GET_PRODUCTS,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_ERROR,
  GET_PRODUCT_BY_ID,
  GET_PRODUCT_BY_ID_SUCCESS,
  GET_PRODUCT_BY_ID_ERROR,
  VERIFICATION_PRODUCT_ID,
  VERIFICATION_PRODUCT_ID_SUCCESS,
  VERIFICATION_PRODUCT_ID_ERROR,
  SAVE_PRODUCT,
  SAVE_PRODUCT_SUCCESS,
  SAVE_PRODUCT_ERROR,
  UPDATE_PRODUCT,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_ERROR,
  DELETE_PRODUCT,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_ERROR,
  ProductReducer,
  ProductEffects,
  selectProducts,
  selectProduct,
};
